# Generated by Django 5.0.6 on 2024-06-07 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('app_menu', models.JSONField(null=True)),
                ('site_menu', models.JSONField(null=True)),
                ('app_configuracao', models.JSONField(null=True)),
                ('site_configuracao', models.JSONField(null=True)),
                ('conta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.conta')),
            ],
            options={
                'db_table': 'conta_configuracao',
            },
        ),
    ]
