# Generated by Django 5.0.6 on 2024-06-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_configuracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('app_menu', models.JSONField(null=True)),
                ('site_menu', models.JSONField(null=True)),
                ('app_configuracao', models.JSONField(null=True)),
                ('site_configuracao', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'conta_configuracaopadrao',
            },
        ),
        migrations.DeleteModel(
            name='Configuracao',
        ),
    ]
