# Generated by Django 5.0.6 on 2024-06-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtocategoria',
            name='url',
            field=models.TextField(null=True),
        ),
    ]
