# Generated by Django 5.0.6 on 2024-06-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_desconto_produto_tipodesconto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='largura',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='profundidade',
        ),
        migrations.AddField(
            model_name='estoque',
            name='is_peso',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='estoque',
            name='is_unidade',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='qtd_real',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
