# Generated by Django 5.0.6 on 2024-08-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
