# Generated by Django 5.0.6 on 2024-08-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_produto_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ordem',
            field=models.IntegerField(null=True),
        ),
    ]
