# Generated by Django 5.0.6 on 2024-08-04 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0005_remove_cliente_endereco_endereco_cliente_and_more'),
        ('produto', '0007_produto_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('usr_insercao', models.IntegerField(blank=True, null=True)),
                ('usr_edicao', models.IntegerField(blank=True, null=True)),
                ('usr_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('session_key', models.CharField(max_length=200, null=True)),
                ('origem', models.CharField(max_length=200, null=True)),
                ('cliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
            ],
            options={
                'db_table': 'cliente_carrinho',
            },
        ),
        migrations.CreateModel(
            name='CarrinhoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('usr_insercao', models.IntegerField(blank=True, null=True)),
                ('usr_edicao', models.IntegerField(blank=True, null=True)),
                ('usr_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('is_entrega', models.BooleanField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('valor_ini', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('quantidade', models.IntegerField(null=True)),
                ('is_cupom', models.BooleanField(default=False, null=True)),
                ('carrinho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carrinho.carrinho')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.produto')),
                ('produto_desconto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.desconto')),
                ('produto_preco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produto.produtopreco')),
            ],
            options={
                'db_table': 'cliente_carrinhoitem',
            },
        ),
    ]
