# Generated by Django 5.0.6 on 2024-08-11 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
        ('cliente', '0005_remove_cliente_endereco_endereco_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.endereco'),
        ),
    ]
