# Generated by Django 5.0.6 on 2024-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontofuncao',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontofuncao',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pontofuncao',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipo',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipo',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipo',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
