# Generated by Django 5.0.6 on 2024-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cliente', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_cliente',
            name='usr_delete',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app_cliente',
            name='usr_edicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='app_cliente',
            name='usr_insercao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
