# Generated by Django 5.0.6 on 2024-06-12 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cliente', '0003_cliente_usr_delete_cliente_usr_edicao_and_more'),
        ('core', '0002_endereco_usr_delete_endereco_usr_edicao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_cliente',
            name='celular_completo_form',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='celular_numero',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='email_documentacao',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='email_financeiro',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='nm_documento_completo',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='nm_documento_primeiro',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='nm_documento_ultimo',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='nm_social_completo',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='nm_social_primeiro',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='nm_social_ultimo',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='passaporte',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='passaporte_form',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='telefone_completo_form',
        ),
        migrations.RemoveField(
            model_name='app_cliente',
            name='telefone_numero',
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_insercao', models.DateTimeField(auto_now_add=True, null=True)),
                ('dat_edicao', models.DateTimeField(auto_now=True, null=True)),
                ('dat_delete', models.DateTimeField(blank=True, null=True)),
                ('usr_insercao', models.IntegerField(blank=True, null=True)),
                ('usr_edicao', models.IntegerField(blank=True, null=True)),
                ('usr_delete', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True, null=True)),
                ('endereco_completo', models.CharField(max_length=250, null=True)),
                ('cep', models.CharField(max_length=8, null=True)),
                ('numero', models.CharField(max_length=30, null=True)),
                ('complemento', models.CharField(max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100, null=True)),
                ('rua', models.CharField(max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100, null=True)),
                ('ponto_referencia', models.CharField(max_length=100, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200, null=True)),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='uf', to='core.estado')),
            ],
            options={
                'db_table': 'cliente_endereco',
            },
        ),
        migrations.AlterField(
            model_name='app_cliente',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='endereco', to='app_cliente.endereco'),
        ),
    ]
