# Generated by Django 5.0.6 on 2024-06-13 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cliente', '0004_remove_cliente_celular_completo_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app_cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='app_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_cliente', to='app_cliente.app_cliente'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='is_principal',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
